---
- name: include common.yml
  include_tasks: common.yml

- name: include_tasks pre_requisite.yml
  include_tasks: pre_requisite.yml
  when: not containerized_deployment

- name: include_tasks openstack-keystone.yml
  include_tasks: openstack-keystone.yml
  when: radosgw_keystone_ssl|bool

- name: include start_radosgw.yml
  include: start_radosgw.yml
  when: not containerized_deployment

- name: include rgw multisite playbooks
  include: multisite/main.yml
  when:
    - rgw_multisite
    - ceph_release_num[ceph_release] >= ceph_release_num.jewel

- name: include docker/main.yml
  include: docker/main.yml
  when: containerized_deployment

- name: create rgw pools if rgw_create_pools is defined
  command: "{{ docker_exec_cmd }} ceph --connect-timeout 5 --cluster {{ cluster }} osd pool create {{ item.key }} {{ item.value.pg_num }}"
  changed_when: false
  with_dict: "{{ rgw_create_pools }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  run_once: true
  when:
    - rgw_create_pools is defined
